# Generated by Django 5.1.7 on 2025-03-27 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftsData',
            fields=[
                ('aircraft_code', models.CharField(db_comment='Aircraft code, IATA', max_length=3, primary_key=True, serialize=False)),
                ('model', models.JSONField(db_comment='Aircraft model')),
                ('range', models.IntegerField(db_comment='Maximal flying distance, km')),
            ],
            options={
                'db_table': 'aircrafts_data',
                'db_table_comment': 'Aircrafts (internal data)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AirportsData',
            fields=[
                ('airport_code', models.CharField(db_comment='Airport code', max_length=3, primary_key=True, serialize=False)),
                ('airport_name', models.JSONField(db_comment='Airport name')),
                ('city', models.JSONField(db_comment='City')),
                ('coordinates', models.TextField(db_comment='Airport coordinates (longitude and latitude)')),
                ('timezone', models.TextField(db_comment='Airport time zone')),
            ],
            options={
                'db_table': 'airports_data',
                'db_table_comment': 'Airports (internal data)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('book_ref', models.CharField(db_comment='Booking number', max_length=6, primary_key=True, serialize=False)),
                ('book_date', models.DateTimeField(db_comment='Booking date')),
                ('total_amount', models.DecimalField(db_comment='Total booking cost', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'bookings',
                'db_table_comment': 'Bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.AutoField(db_comment='Flight ID', primary_key=True, serialize=False)),
                ('flight_no', models.CharField(db_comment='Flight number', max_length=6)),
                ('scheduled_departure', models.DateTimeField(db_comment='Scheduled departure time')),
                ('scheduled_arrival', models.DateTimeField(db_comment='Scheduled arrival time')),
                ('status', models.CharField(db_comment='Flight status', max_length=20)),
                ('actual_departure', models.DateTimeField(blank=True, db_comment='Actual departure time', null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, db_comment='Actual arrival time', null=True)),
            ],
            options={
                'db_table': 'flights',
                'db_table_comment': 'Flights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_no', models.CharField(db_comment='Ticket number', max_length=13, primary_key=True, serialize=False)),
                ('passenger_id', models.CharField(db_comment='Passenger ID', max_length=20)),
                ('passenger_name', models.TextField(db_comment='Passenger name')),
                ('contact_data', models.JSONField(blank=True, db_comment='Passenger contact information', null=True)),
            ],
            options={
                'db_table': 'tickets',
                'db_table_comment': 'Tickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('aircraft_code', models.OneToOneField(db_column='aircraft_code', db_comment='Aircraft code, IATA', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='flight.aircraftsdata')),
                ('seat_no', models.CharField(db_comment='Seat number', max_length=4)),
                ('fare_conditions', models.CharField(db_comment='Travel class', max_length=10)),
            ],
            options={
                'db_table': 'seats',
                'db_table_comment': 'Seats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketFlights',
            fields=[
                ('ticket_no', models.OneToOneField(db_column='ticket_no', db_comment='Ticket number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='flight.tickets')),
                ('fare_conditions', models.CharField(db_comment='Travel class', max_length=10)),
                ('amount', models.DecimalField(db_comment='Travel cost', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ticket_flights',
                'db_table_comment': 'Flight segment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoardingPasses',
            fields=[
                ('ticket_no', models.OneToOneField(db_column='ticket_no', db_comment='Ticket number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='flight.ticketflights')),
                ('flight_id', models.IntegerField(db_comment='Flight ID')),
                ('boarding_no', models.IntegerField(db_comment='Boarding pass number')),
                ('seat_no', models.CharField(db_comment='Seat number', max_length=4)),
            ],
            options={
                'db_table': 'boarding_passes',
                'db_table_comment': 'Boarding passes',
                'managed': False,
            },
        ),
    ]
